config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root "events#index"
    resources :events
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "events#index"
  resources :events
  resources :participants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :participants, dependent: :destroy

  scope :active, -> { where('open_date >= ?', Date.current) }
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :event
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  def index
    @events = Event.all.order(:id)
  end

  def new
    @event = Event.new
  end

  def create
    event = Event.create!(event_params)

    redirect_to admin_events_path
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    event = Event.find(params[:id])
    event.update!(event_params)

    redirect_to admin_events_path
  end

  def event_params
    params.require(:event).permit(:title, :place, :note, :open_date, :start_time, :end_time, :kind)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def index
    @events = Event.active.order(:open_date)
  end

  def create
    event = Event.create!(event_params)

    redirect_to events_url
  end

  def show
    @event = Event.find(params[:id])
    @participants = @event.participants.order(:id)
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    event = Event.find(params[:id])
    event.update!(event_params)

    redirect_to events_url
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy

    redirect_to events_url, status: :see_other
  end

  private

  def event_params
    params.require(:event).permit(:title, :place, :note, :open_date, :start_time, :end_time, :kind)
  end

end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  def new
    @participant = Participant.new
  end

  def create
    participant = Participant.create!(participant_params)

    redirect_to event_url(participant.event)
  end

  def edit
    @participant = Participant.find(params[:id])
  end

  def update
    participant = Participant.find(params[:id])
    participant.update!(participant_params)

    redirect_to event_url(participant.event)
  end

  def destroy
    participant = Participant.find(params[:id])
    participant.destroy

    redirect_to event_url(participant.event), status: :see_other
  end

  private

  def participant_params
    params.require(:participant).permit(:event_id, :name)
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/admin/events/_form.html.erb
<%= form_with model: [:admin, @event] do |form| %>
  <div class="mb-3">
    <%= form.label :title, "Tiêu đề", class: "form-label" %>
    <%= form.text_field :title, class: "form-control", required: true %>
  </div>
  <div class="mb-3">
    <%= form.label :place, "Địa chỉ", class: "form-label" %>
    <%= form.text_field :place, class: "form-control", required: true %>
  </div class="mb-3">
  <div class="mb-3">
    <%= form.label :note, "Ghi chú", class: "form-label" %>
    <%= form.text_area :note, rows: 3, class: "form-control" %>
  </div>
  <div class="mb-3 row">
    <div class="col-md-12">
      <%= form.label :open_date, "Thời gian", class: "form-label" %>
    </div>
    <div class="mb-3 col-md-6">
      <%= form.date_field :open_date, class: "form-control", required: true %>
    </div>
    <div class="mb-3 col-md-3">
      <%= form.time_field :start_time, class: "form-control", required: true %>
    </div>
    <div class="mb-3 col-md-3">
      <%= form.time_field :end_time, class: "form-control", required: true %>
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      <%= form.submit "OK", class: "btn btn-outline-success form-control col-md-6" %>
    </div>
    <div class="col-6">
      <%= link_to "Huỷ", :back, class: "btn btn-outline-danger form-control col-md-6" %>
    </div>
  </div>
<% end %>

app/views/admin/events/index.html.erb
<h1>DANH SÁCH HOẠT ĐỘNG CỦA CLB</h1>
<%= link_to 'Thêm mới', new_admin_event_url, class: 'btn btn-outline-success col-12 mb-3' %>
<% @events.each do |event| %>
  <div class="event-item card mb-3">
    <div class="card-body">
      <h5 class="card-title"><%= event.title %></h5>
      <h6 class="card-subtitle mb-2 text-muted event-item-place">
        <i class="bi bi-map"></i><%= event.place %>
        <%= link_to "https://www.google.com/maps/search/?api=1&query=#{event.place}", target: '_blank' do %>
          <i class="bi bi-box-arrow-up-right"></i>
        <% end %>
      </h6>
      <h6 class="card-subtitle mb-2 text-muted"><i class="bi bi-calendar-event"></i><%= "#{event.open_date} #{event.start_time.strftime('%H:%M')} ~ #{event.end_time.strftime('%H:%M')}" %></h6>
      <p class="card-text"><%= event.note %></p>
      <%= link_to 'Sửa', edit_admin_event_url(event), class: 'card-link' %>
    </div>
  </div>
<% end %>

app/views/events/_form.html.erb
<%= form_with model: @event do |form| %>
  <div class="mb-3">
    <%= form.label :title, "Tiêu đề", class: "form-label" %>
    <%= form.text_field :title, class: "form-control", required: true %>
  </div>
  <div class="mb-3">
    <%= form.label :place, "Địa chỉ", class: "form-label" %>
    <%= form.text_field :place, class: "form-control", required: true %>
  </div class="mb-3">
  <div class="mb-3">
    <%= form.label :note, "Ghi chú", class: "form-label" %>
    <%= form.text_area :note, rows: 3, class: "form-control" %>
  </div>
  <div class="mb-3 row">
    <div class="col-md-12">
      <%= form.label :open_date, "Thời gian", class: "form-label" %>
    </div>
    <div class="mb-3 col-12">
      <%= form.date_field :open_date, class: "form-control", required: true %>
    </div>
    <div class="mb-3 col-5">
      <%= form.time_field :start_time, class: "form-control", required: true %>
    </div>
    <div class="mb-3 col-2 text-center">
      ~
    </div>
    <div class="mb-3 col-5">
      <%= form.time_field :end_time, class: "form-control", required: true %>
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      <%= form.submit "OK", class: "btn btn-outline-success form-control col-md-6" %>
    </div>
    <div class="col-6">
      <%= link_to "Huỷ", :back, class: "btn btn-outline-danger form-control col-md-6" %>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1 class="mb-5">SỬA HOẠT ĐỘNG</h1>
<%= render 'form' %>

app/views/events/index.html.erb
<h1>DANH SÁCH HOẠT ĐỘNG CỦA CLB</h1>
<%= link_to 'Thêm hoạt động', new_event_url, class: 'btn btn-outline-success mb-3 col-12' %>
<% @events.each do |event| %>
  <div class="event-item card mb-3">
    <div class="card-body">
      <h5 class="card-title"><%= event.title %></h5>
      <h6 class="card-subtitle mb-2 text-muted event-item-place">
        <i class="bi bi-map"></i><%= event.place %>
        <%= link_to "https://www.google.com/maps/search/?api=1&query=#{event.place}", target: '_blank' do %>
          <i class="bi bi-box-arrow-up-right"></i>
        <% end %>
      </h6>
      <h6 class="card-subtitle mb-2 text-muted">
        <i class="bi bi-calendar-event"></i>
        <%= "#{event.open_date} (#{I18n.l(event.open_date, format: '%a')}) #{event.start_time.strftime('%H:%M')} ~ #{event.end_time.strftime('%H:%M')}" %>
      </h6>
      <p class="card-text"><%= event.note %></p>
      <%= link_to 'Chi tiết', event, class: 'card-link' %>
      <%= link_to 'Đăng ký', new_participant_url(event_id: event.id), class: 'card-link' %>
      <%= link_to 'Sửa', edit_event_url(event), class: 'card-link' %>
    </div>
  </div>
<% end %>

app/views/events/new.html.erb
<h1>THÊM HOẠT ĐỘNG</h1>
<%= render 'form' %>

app/views/events/show.html.erb
<%= link_to root_url, class: 'btn btn-outline-dark mb-3' do %>
  <i class="bi bi-arrow-left"></i> Trở về
<% end %>
<div class="event-item card mb-5">
  <div class="card-body">
    <h5 class="card-title"><%= @event.title %></h5>
    <h6 class="card-subtitle mb-2 text-muted event-item-place">
      <i class="bi bi-map"></i><%= @event.place %>
    <%= link_to "https://www.google.com/maps/search/?api=1&query=#{@event.place}", target: '_blank' do %>
      <i class="bi bi-box-arrow-up-right"></i>
    <% end %>
    </h6>
    <h6 class="card-subtitle mb-2 text-muted"><i class="bi bi-calendar-event"></i><%= "#{@event.open_date} #{@event.start_time.strftime('%H:%M')} ~ #{@event.end_time.strftime('%H:%M')}" %></h6>
    <p class="card-text"><%= @event.note %></p>
  </div>
<div class="row m-1 mb-3">
  <div class="col-6">
    <%= link_to 'Sửa', edit_event_url(@event), class: 'btn btn-outline-warning col-12' %>
  </div>
  <div class="col-6">
    <%= link_to 'Xoá', event_url(@event), data: {
      turbo_method: :delete,
      turbo_confirm: 'Bạn có chắc chắn muốn xoá không?'
    }, class: 'btn btn-outline-danger col-12' %>
  </div>
</div>
</div>
<h5 class="mb-3">Danh sách người tham gia</h5>
<div class="row mb-3">
  <div class="col-12">
    <%= link_to 'Đăng ký', new_participant_url(event_id: @event.id), class: 'btn btn-outline-success col-12' %>
  </div>
</div>
<% @participants.each.with_index(1) do |participant, index| %>
  <div>
    <%= "#{index}. #{participant.name}" %>
    <span class='action-btn'>
      <%= link_to edit_participant_url(participant), class: 'btn-edit' do %>
        <i class="bi bi-pencil-square"></i>
      <% end %>
      <%= link_to participant_url(participant), data: {
        turbo_method: :delete,
        turbo_confirm: 'Bạn có chắc chắn muốn xoá không?'
      }, class: 'btn-destroy' do %>
        <i class="bi bi-trash"></i>
      <% end %>
    </span>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kawaguchi Badminton Club</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="container">
    <div class="row justify-content-md-center">
      <div class='col-md-5'>
        <%= render 'shared/navbar' %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/participants/_form.html.erb
<%= form_with model: @participant do |form| %>
  <%= form.hidden_field :event_id, value: params[:event_id] || @participant.event_id %>
  <%= form.label :name, 'Họ Tên', class: 'form-label' %>
  <%= form.text_field :name, class: 'form-control mb-3' %>
  <div class="row">
    <div class="col-6">
      <%= form.submit "OK", class: "btn btn-outline-success form-control col-md-6" %>
    </div>
    <div class="col-6">
      <%= link_to "Huỷ", :back, class: "btn btn-outline-danger form-control col-md-6" %>
    </div>
  </div>
<% end %>

app/views/participants/edit.html.erb
<h1>SỬA THÔNG TIN NGƯỜI THAM DỰ</h1>
<%= render 'form' %>

app/views/participants/new.html.erb
<h1>THÊM NGƯỜI THAM DỰ</h1>
<%= render 'form' %>

app/views/shared/_navbar.html.erb
<% url = request.fullpath.include?('admin') ? admin_root_url : root_url %>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= url %>">Kawaguchi</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= url %>">Trang chủ</a>
        </li>
      </ul>
    </div>
  </div>
</nav>